---
##################################################################################################################
# MQTT Light
# The mqtt light platform lets you control your MQTT enabled lights through one of the supported message
# schemas, default, json or template.
#
# URL: https://www.home-assistant.io/integrations/light.mqtt/
#
# EntityID: light.bedroom_nico_multisensor
##################################################################################################################
platform: mqtt
schema: json
name: Bedroom Nico MultiSensor
state_topic: 532B98/light/state
command_topic: 532B98/light/set
availability_topic: 532B98/status
brightness: true
rgb: true
optimistic: false
qos: 0
