---
##################################################################################################################
# MQTT Light
# The mqtt light platform lets you control your MQTT enabled lights through one of the supported message
# schemas, default, json or template.
#
# Device: MultiSensor 02 - ESP_52FAE3 (Kitchen)
# URL: https://www.home-assistant.io/integrations/light.mqtt/
#
# EntityID: light.kitchen_multisensor
##################################################################################################################
platform: mqtt
name: Kitchen MultiSensor
state_topic: 52FAE3/light/state
command_topic: 52FAE3/light/set
availability_topic: 52FAE3/status
schema: json
brightness: true
rgb: true
optimistic: false
qos: 0
