---
##################################################################################################################
# MQTT Light
# The mqtt light platform lets you control your MQTT enabled lights through one of the supported message
# schemas, default, json or template.
#
# Device: MultiSensor 01 - ESP_536310
# URL: https://www.home-assistant.io/integrations/light.mqtt/
#
# EntityID: light.living_room_multisensor
##################################################################################################################
platform: mqtt
schema: json
name: Living Room MultiSensor
state_topic: 536310/light/state
command_topic: 536310/light/set
availability_topic: 536310/status
brightness: true
rgb: true
optimistic: false
qos: 0
