---
##################################################################################################################
# MQTT Light
# The mqtt light platform lets you control your MQTT enabled lights through one of the supported message
# schemas, default, json or template.
#
# Device: Zemismart KS-811 3 Gang Switch - button 1
# URL: https://www.home-assistant.io/integrations/light.mqtt/
#
# EntityID: light.living_room_ceiling
##################################################################################################################
platform: mqtt
name: Living Room Ceiling
state_topic: stat/ks811_721BEC/POWER1
command_topic: cmnd/ks811_721BEC/POWER1
availability_topic: tele/ks811_721BEC/LWT
payload_on: "ON"
payload_off: "OFF"
payload_available: Online
payload_not_available: Offline
qos: 1
retain: false
