---
##############################################################################################
# MQTT Binary Sensor
# The mqtt binary sensor platform uses an MQTT message received to set the binary sensor’s
# state to on or off.
#
# URL: https://www.home-assistant.io/integrations/binary_sensor.mqtt/
#
# EntityID: binary_sensor.doorbell
##############################################################################################
platform: mqtt
name: doorbell
state_topic: A579B6/sensor/doorbell
availability_topic: A579B6/status
device_class: sound
