---
##############################################################################################
# Template Binary Sensor
# The template platform supports binary sensors which get their values from other entities.
# The state of a Template Binary Sensor can only be on or off.
#
# URL: https://www.home-assistant.io/integrations/binary_sensor.template
#
# EntityID: binary_sensor.living_room_motion
##############################################################################################
platform: template
sensors:
  living_room_motion:
    friendly_name: Living Room Motion
    device_class: motion
    value_template: >-
      {{ is_state('binary_sensor.lrc_ai_motion', 'on') }}
    # value_template: >-
    #   {{ is_state('binary_sensor.living_room_multisensor_motion', 'on')
    #       or is_state('binary_sensor.lrc_ai_motion', 'on') }}
