---
custom_header:
  compact_mode: true
  button_text:
    options: "{{ hours24 }}:{{ minutesLZ }}"

title: Admin
views:
  - !include lovelace/views/system.yaml
  - !include lovelace/views/settings.yaml
  - !include lovelace/views/cctv_triggered.yaml
  - !include lovelace/views/docker.yaml
  - !include lovelace/views/labs.yaml
