---
custom_header:
  compact_mode: true
  button_text:
    options: "{{ hours24 }}:{{ minutesLZ }}"

title: Admin
views:
  - !include lovelace/views/system.yaml
  - !include lovelace/views/settings.yaml
  - !include lovelace/views/cctv_triggered.yaml
  - !include lovelace/views/labs.yaml
  - !include lovelace/views/docker.yaml

  - badges: []
    cards:
      - entities:
          - head:
              label: Home Assistant
              type: section
            items:
              - sensor.version_available
              - sensor.version_current
              - sensor.uptime
              - binary_sensor.remote_ui
            type: custom:fold-entity-row
          - head: sensor.ha_dockermon_mosquitto
            items:
              - sensor.mosquitto_current_version
              - sensor.mosquitto_docker_latest_image_build
              - entity: switch.ha_dockermon_mosquitto
                name: pause / run
            type: custom:fold-entity-row
          - head: sensor.ha_dockermon_influxdb
            items:
              - entity: switch.ha_dockermon_influxdb
                name: pause / run
            type: custom:fold-entity-row
          - head: zwave.aeon_labs_zw090_z_stick_gen5_au
            items:
              - zwave.bathroom_multisensor_zw100
              - zwave.office_zw100_multisensor_zw100
              - zwave.hall_downlights
              - zwave.bathroom_downlights
            type: custom:fold-entity-row
          - head: binary_sensor.swartninja02_connectivity
            items:
              - entity: script.shutdown_swartninja02
                name: Shutdown
              - switch.deluge_switch
              - sensor.deluge_down_speed
              - sensor.deluge_up_speed
              - sensor.deluge_status
            type: custom:fold-entity-row
          - head: binary_sensor.swartninja03_connectivity
            items:
              - entity: sensor.blue_iris_state
              - input_boolean.blue_iris
            type: custom:fold-entity-row
          - head: sensor.office_door_system_e449d3_availability
            items:
              - binary_sensor.office_door_system_door
              - sensor.office_door_system_wifi
              - lock.office_door_system_lock
              - cover.office_door_system_cover
              - switch.office_door_system_siren
            type: custom:fold-entity-row
        show_header_toggle: false
        title: Systems
        type: entities

      - cards:
          - cards:
              - aggregate_func: max
                entities:
                  - entity: sensor.glances_cpu_used
                    line_color: "#14ff8d"
                    name: System
                  - entity: sensor.glances_containers_cpu_used
                    line_color: "#2814ff"
                    name: Containers
                font_size: 65
                font_size_header: 9
                hours_to_show: 7
                line_width: 2
                name: CPU Usage
                points_per_hour: 10
                show:
                  average: true
                  extrema: true
                smoothing: false
                style: |
                  ha-card {
                    background: var(--paper-card-background-color);
                    color: var(--primary-text-color);
                    border-radius: var(--border-radius);
                    box-shadow: var(--box-shadow)
                  }
                type: custom:mini-graph-card
                update_interval: 30
              - aggregate_func: max
                entities:
                  - entity: sensor.glances_ram_used
                    line_color: "#14ff8d"
                    name: System
                  - entity: sensor.glances_containers_ram_used
                    line_color: "#2814ff"
                    name: Containers
                font_size: 65
                font_size_header: 9
                hours_to_show: 7
                line_width: 2
                name: RAM Usage
                points_per_hour: 10
                show:
                  average: true
                  extrema: true
                smoothing: false
                style: |
                  ha-card {
                    background: var(--paper-card-background-color);
                    color: var(--primary-text-color);
                    border-radius: var(--border-radius);
                    box-shadow: var(--box-shadow)
                  }
                type: custom:mini-graph-card
                update_interval: 30
            parameters:
              pagination:
                dynamicBullets: true
                type: bullets
              spaceBetween: 8
              touchEventsTarget: container
            type: custom:swipe-card
        type: horizontal-stack
    path: todo
    title: TODO
