# lovelace_gen
type: custom:auto-entities
filter:
  include:
    - entity_id: "{{ include_entity_id }}"
      sort:
        method: name
        numeric: true
show_empty: false
sort:
  method: domain
  numeric: true
card:
  type: {{ type|default('entities') }}
  title: "{{ title }}"
  show_header_toggle: {{ show_header_toggle|default('false') }}