# lovelace_gen
type: custom:cover-control-button-row
name: "{{ name }}"
icon: "{{ icon }}"
entity: {{ entity }}
reverseButtons: true
customTheme: true
stopButtonColor: var(--accent-color)
buttonInactiveColor: var(--primary-color)
isOpenedColor: var(--dark-primary-color)
isClosedColor: var(--dark-primary-color)
customOpenText: OPEN
customStopText: STOP
customCloseText: CLOSE
style: |
  button.position {
    border: 1px solid var(--primary-background-color);
  }