---
#
# List of entities that is exposed to Alexa
# From area: Bedroom Master
#
- light.bedroom_master_ceiling
- switch.bedroom_master_electric_blanket_dick
- switch.bedroom_master_electric_blanket_tamara
