---
##############################################################################################
# MQTT Sensor
# This mqtt sensor platform uses the MQTT message payload as the sensor value.
#
# URL: https://www.home-assistant.io/integrations/sensor.mqtt/
#
# EntityID: sensor.bedroom_nico_electric_blanket_current
##############################################################################################
platform: mqtt
name: Bedroom Nico Electric Blanket Current
state_topic: tele/sonoff_374EE5/SENSOR
value_template: "{{ value_json['ENERGY']['Current'] }}"
unit_of_measurement: A
