---
##############################################################################################
# MQTT Sensor
# This mqtt sensor platform uses the MQTT message payload as the sensor value.
#
# URL: https://www.home-assistant.io/integrations/sensor.mqtt/
#
# EntityID: sensor.bedroom_nico_multisensor_wifi
##############################################################################################
platform: mqtt
name: Bedroom Nico MultiSensor WiFi
state_topic: 532B98/sensor/wifi
unit_of_measurement: "%"
availability_topic: 532B98/status
payload_available: online
payload_not_available: offline
