---
##############################################################################################
# Deluge
# The deluge platform allows you to monitor your downloads with Deluge from within Home Assistant
# and setup automation based on the information.
#
# URL: https://www.home-assistant.io/integrations/deluge#sensor
##############################################################################################
platform: deluge
host: 192.168.1.214
username: !secret deluge_daemon_username
password: !secret deluge_daemon_password
monitored_variables:
  - current_status
  - download_speed
  - upload_speed
