---
##############################################################################################
# MQTT Sensor
# This mqtt sensor platform uses the MQTT message payload as the sensor value.
#
# URL: https://www.home-assistant.io/integrations/sensor.mqtt/
##############################################################################################
platform: mqtt
name: Living Room MultiSensor WiFi
state_topic: 536310/sensor/wifi
unit_of_measurement: "%"
availability_topic: 536310/status
payload_available: online
payload_not_available: offline
