---
##############################################################################################
# MQTT Sensor
# This mqtt sensor platform uses the MQTT message payload as the sensor value.
#
# URL: https://www.home-assistant.io/integrations/sensor.mqtt/
#
# EntityID: sensor.man_cave_multisensor_humidity
##############################################################################################
platform: mqtt
name: Man Cave MultiSensor Humidity
state_topic: 535210/sensor/humidity
unit_of_measurement: "%"
availability_topic: 535210/status
payload_available: online
payload_not_available: offline
