---
##############################################################################################
# MQTT Sensor
# This mqtt sensor platform uses the MQTT message payload as the sensor value.
#
# URL: https://www.home-assistant.io/integrations/sensor.mqtt/
#
# EntityID: sensor.man_cave_multisensor_real_feel
##############################################################################################
platform: mqtt
name: Man Cave MultiSensor Real Feel
state_topic: 535210/sensor/realfeel
unit_of_measurement: °C
availability_topic: 535210/status
payload_available: online
payload_not_available: offline
