---
##############################################################################################
# Template
# The template platform supports sensors which get their values from other entities.
#
# URL: https://www.home-assistant.io/integrations/template
#
# EntityID: sensor.presence_location_dick
##############################################################################################
platform: template
sensors:
  presence_location_dick:
    friendly_name: Dick
    entity_picture_template: /local/images/misc/dick.jpg
    value_template: >-
      {% if is_state('input_boolean.presence_location_away_dick', 'on') %}
        Away (Override)
      {% else %}
        {{ states('person.dick') | title }}
      {% endif %}
