---
##################################################################################################################
# MQTT Switch
# The mqtt switch platform lets you control your MQTT enabled switches.
#
# URL: https://www.home-assistant.io/integrations/switch.mqtt/
#
# Device: NodeMCU E449D3 office_door_system
# EntityID: switch.office_door_system_siren
##################################################################################################################
platform: mqtt
unique_id: office_door_system_e449d3_siren
name: Office Door System Siren
icon: mdi:alarm-bell
state_topic: E449D3/siren/state
command_topic: E449D3/siren/set
availability_topic: E449D3/availability/state
payload_available: online
payload_not_available: offline
qos: 1
retain: true
