---
id: kitchen_light_off_motion
alias: Kitchen Light Off Motion
description: Turn off kitchen light 3 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion
  to: 'off'
  for:
    minutes: 3
condition:
  - condition: template
    value_template: "{{ is_state('light.kitchen_side', 'on') or is_state('light.kitchen_ceiling', 'on') }}"
action:
  - service: light.turn_off
    entity_id:
      - light.kitchen_side
      - light.kitchen_ceiling
