---
esphome:
  name: ${node_name}
  comment: "D1Mini: ${node_comment}"
  platform: ESP8266
  board: d1_mini
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - <<: !include sensor/uptime.config.yaml
  - <<: !include sensor/wifi_signal.config.yaml

binary_sensor:
  - <<: !include binary_sensor/connection_status.config.yaml

text_sensor:
  - <<: !include text_sensor/version.config.yaml