esphome:
  name: ${node_name}
  comment: ${node_comment}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  esp8266_restore_from_flash: true
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - <<: !include sensor/uptime.config.yaml
  - <<: !include sensor/wifi_signal.config.yaml

binary_sensor:
  - <<: !include binary_sensor/connection_status.config.yaml
  # Button on the Sonoff Basic
  - platform: gpio
    id: button_01
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_01
  - platform: gpio
    id: button_02
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_02

text_sensor:
  - <<: !include text_sensor/version.config.yaml

switch:
  - platform: gpio
    pin: GPIO13
    id: relay_01
    name: ${device_verbose_name} 01
    icon: ${switch_icon}
  - platform: gpio
    pin: GPIO14
    id: relay_02
    name: ${device_verbose_name} 02
    icon: ${switch_icon}

status_led:
  pin:
    number: GPIO4
    inverted: yes
