esphome:
  name: ${node_name}
  platform: ESP8266
  board: nodemcuv2
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - <<: !include sensor/uptime.config.yaml
  - <<: !include sensor/wifi_signal.config.yaml

binary_sensor:
  - <<: !include binary_sensor/connection_status.config.yaml

text_sensor:
  - <<: !include text_sensor/version.config.yaml