---
esphome:
  name: ${node_name}
  comment: "Zemismart KS811 3 Gang: ${node_comment}"
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: GPIO2
    inverted: true
