# lovelace_gen
# Available parameters:
# node_name   (required)
# entity_name  (optional)
head:
  entity: binary_sensor.{{ node_name }}_status
{% if entity_name %}
  name: {{entity_name}}
{% else %}
  name: Sonoff Basic
{% endif %}
type: 'custom:fold-entity-row'
items:
  - entity: switch.{{ node_name }}
    name: Switchs
  - entity: sensor.{{ node_name }}_wifi_signal
    name: WiFi
  - entity: binary_sensor.{{ node_name }}_status
    name: Status
  - entity: sensor.{{ node_name }}_uptime
    name: Uptime
  - entity: sensor.{{ node_name }}_esphome_version
    name: ESPHome Version
  - entity: switch.{{ node_name }}_restart
    name: Restart
