---
icon: mdi:shower
panel: true
path: bathroom
title: Bathroom
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:shower"></ha-icon> Bathroom

      - type: vertical-stack
        cards:
          - name: Ceiling
            type: light
            entity: light.bathroom_zw111_nano_dimmer
          - type: horizontal-stack
            cards:
              - name: Fan
                type: custom:button-card
                entity: fan.bathroom
              - type: custom:button-card
                template: motion_sensor_btn
                entity: binary_sensor.bathroom_multisensor_motion

      - break

      - !include
        - ../templates/esphome_multisensor_graphs.yaml
        - node_name: bathroom_multisensor

      - break

      - !include
        - ../templates/esphome_multisensor_entities.yaml
        - node_name: bathroom_multisensor
          show_led: false
          show_door: true
          show_motion: true

      - title: Hall ZW111 Nano Dimmer
        type: entities
        show_header_toggle: false
        entities:
          - entity: zwave.bathroom_zw111_nano_dimmer
          - entity: light.bathroom_zw111_nano_dimmer
            name: Light
          - entity: sensor.bathroom_zw111_nano_dimmer_current
            name: Current
          - entity: sensor.bathroom_zw111_nano_dimmer_energy
            name: Energy
          - entity: sensor.bathroom_zw111_nano_dimmer_power
            name: Power
          - entity: sensor.bathroom_zw111_nano_dimmer_previous_reading
            name: Previous reading
          - entity: sensor.bathroom_zw111_nano_dimmer_voltage
            name: Voltage
