---
title: Labs
icon: mdi:test-tube
path: admin-labs
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - !include
        - ../templates/header/view_heading.yaml
        - title: <ha-icon icon="mdi:test-tube"></ha-icon> Labs


      - break

      - title: Lights On
        show_header_toggle: false
        type: entities
        entities:
          - type: custom:auto-entities
            show_empty: false
            filter:
              include:
                - domain: light
                  state: "on"
                  area: Kitchen
            card:
              type: custom:fold-entity-row
              head:
                type: section
                label: Automatically populated
