---
icon: mdi:human-male-female
panel: true
path: bedroom_master
title: Master bedroom
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/header/view_heading.yaml
            - title: <ha-icon icon="mdi:human-male-female"></ha-icon> Master bedroom

          - entity: light.bedroom_master_ceiling
            icon: mdi:ceiling-light
            name: Main
            type: light

          - type: horizontal-stack
            cards:
              - !include
                - '../templates/button/button.yaml'
                - entity: switch.bedroom_master_electric_blanket_tamara
                  name: Tamara
              - !include
                - '../templates/button/button.yaml'
                - entity: switch.bedroom_master_electric_blanket_dick
                  name: Dick
              - !include
                - '../templates/button/button.yaml'
                - entity: binary_sensor.bedroom_master_multisensor_motion
                  grid: grid-alternative
                  style: style-alternative
                  name: Motion
                  show_state: true
                  btn_template: style-transparent
                  icon_on: mdi:motion-sensor
                  icon_color_on: var(--accent-color)
                  icon_off: mdi:walk
                  icon_color_off: var(--dark-primary-color)

      - break

      - !include
        - ../templates/esphome_multisensor_graphs.yaml
        - node_name: bedroom_master_multisensor

      - break

      - type: custom:mini-media-player
        entity: media_player.bedroom_master_apple_tv
        icon: mdi:apple
        artwork: cover
        name: Apple TV


      - !include
        - ../templates/esphome_multisensor_entities.yaml
        - node_name: bedroom_master_multisensor
          show_led: true
          show_door: false
          show_motion: true

