---
icon: mdi:human-male-female
panel: true
path: bedroom_master
title: Master bedroom
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:human-male-female"></ha-icon> Master bedroom

          - entity: light.bedroom_master_ceiling
            icon: mdi:ceiling-light
            name: Main
            type: light

          - type: horizontal-stack
            cards:
              - name: Tamara Bed
                type: entity-button
                entity: switch.bedroom_master_electric_blanket_tamara
              - name: Dick Bed
                type: entity-button
                entity: switch.bedroom_master_electric_blanket_dick
              - entity: binary_sensor.bedroom_master_multisensor_motion
                type: custom:button-card
                template: motion_sensor_btn

      - break

      - !include
        - ../templates/esphome_multisensor_graphs_card.yaml
        - node_name: bedroom_master_multisensor

      - break

      - type: custom:mini-media-player
        entity: media_player.bedroom_master_apple_tv
        icon: mdi:apple
        artwork: cover
        name: Apple TV

      - !include
        - ../templates/esphome_multisensor_entities_card.yaml
        - node_name: bedroom_master_multisensor
          show_led: true
          show_door: false
          show_motion: true

