---
title: Max bedroom
icon: mdi:alpha-m-box
panel: true
path: max_bedroom
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:alpha-m-box"></ha-icon> Max bedroom

          - type: horizontal-stack
            cards:
              - entity: light.bedroom_max_ceiling
                name: Ceiling
                type: custom:button-card
              - entity: switch.bedroom_max_electric_blanket
                name: Bed
                type: custom:button-card

          - cards:
              - entity: light.ampersand_multisensor_light
                name: MultiSensor
                type: entity-button
            type: horizontal-stack

      - break

      - type: vertical-stack
        cards:
          - entities:
              - name: Room Temperature
                color: var(--light-primary-color)
                entity: sensor.ampersand_multisensor_temperature
              - entity: sensor.dark_sky_temperature
                color: var(--dark-primary-color)
                name: Outside Temperature
            font_size: 75
            line_width: 3
            type: custom:mini-graph-card
          - cards:
              - entities:
                  - entity: sensor.ampersand_multisensor_humidity
                    name: Humidity
                font_size: 75
                line_color: var(--complement-color-one)
                line_width: 3
                type: custom:mini-graph-card
              - entities:
                  - entity: sensor.ampersand_multisensor_luminance
                    name: Luminance
                font_size: 75
                line_color: var(--complement-color-two)
                line_width: 3
                type: custom:mini-graph-card
            type: horizontal-stack

      - break

      - title: MultiSensor
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.ampersand_multisensor_light
            name: LED
          - entity: sensor.ampersand_multisensor_temperature
            name: Temperature
          - entity: sensor.ampersand_multisensor_humidity
            name: Humidity
          - entity: sensor.ampersand_multisensor_luminance
            name: Luminance
          - entity: sensor.ampersand_multisensor_wifi_signal
            name: WiFi
          - entity: sensor.ampersand_multisensor_uptime
            name: Uptime
          - entity: sensor.ampersand_multisensor_esphome_version
            name: ESPHome Version

      - title: Electric Blanket
        type: entities
        show_header_toggle: false
        entities:
          - entity: switch.bedroom_max_electric_blanket
            name: Switch
          - entity: sensor.bedroom_max_electric_blanket_current
            name: Current
          - entity: sensor.bedroom_max_electric_blanket_energy
            name: Energy
          - entity: sensor.bedroom_max_electric_blanket_power
            name: Power
          - entity: sensor.bedroom_max_electric_blanket_power_factor
            name: Power factor
          - entity: sensor.bedroom_max_electric_blanket_voltage
            name: Voltage
