---
title: System
path: admin-system
icon: mdi:desktop-tower-monitor
panel: true
popup_cards:
  switch.docker_esphome:
    title: ""
    style:
      $: |
        .mdc-dialog .mdc-dialog__container {
          width: 100%;
        }
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
          width:100%;
          box-shadow:none;
        }
      .: |
        :host {
          --mdc-theme-surface: rgba(0,0,0,0);
          --secondary-background-color: rgba(0,0,0,0);
          --ha-card-background: rgba(0,0,0,0);
          --mdc-dialog-scrim-color: rgba(0,0,0,0.8);
          --mdc-dialog-min-height: 100%;
          --mdc-dialog-min-width: 100%;
          --mdc-dialog-max-width: 100%;
        }
        mwc-icon-button {
          color: #FFF;
        }
    card:
      type: custom:light-popup-card
      entity: light.living_room_mood
      icon: mdi:led-strip
      actionsInARow: 2
      brightnessWidth: 150px
      brightnessHeight: 400px
      switchWidth: 150px
      switchHeight: 400px
      actions:
        - service: scene.turn_on
          service_data:
            entity_id: scene.ontspannen
          color: "#FDCA64"
          name: ontspannen
        - service: scene.turn_on
          service_data:
            entity_id: scene.helder
          color: "#FFE7C0"
          name: helder
        - service: scene.turn_on
          service_data:
            entity_id: scene.concentreren
          color: "#BBEEF3"
          name: concentreren
        - service: scene.turn_on
          service_data:
            entity_id: scene.energie
          color: "#8BCBDD"
          name: energie
  switch.docker_mosquitto:
    title: My popup
    card:
      type: custom:auto-entities
      card:
        type: entities
        show_header_toggle: false
      filter:
        include:
          - entity_id: "*.docker_mosquitto*"

cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - title: Home Assistant
        type: glance
        entities:
          - entity: sensor.version_current
            name: Version
          - entity: sensor.uptime
          - entity: binary_sensor.remote_ui

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                name: CPU
                unit: "%"
                entity: sensor.glances_cpu_used
                severity:
                  green: 0
                  yellow: 45
                  red: 85
              - type: gauge
                name: Temp
                unit: °C
                entity: sensor.cpu_temp
                severity:
                  green: 0
                  yellow: 60
                  red: 85
          - type: horizontal-stack
            cards:
              - type: gauge
                name: RAM
                unit: "%"
                entity: sensor.glances_ram_used_percent
                severity:
                  green: 0
                  yellow: 45
                  red: 85
              - type: gauge
                name: Swap
                unit: "%"
                entity: sensor.glances_swap_used_percent
                severity:
                  green: 0
                  yellow: 45
                  red: 85

      - type: custom:swipe-card
        parameters:
          spaceBetween: 8
          touchEventsTarget: container
          pagination:
            type: bullets
            dynamicBullets: true
        cards:
          - name: CPU Usage
            type: custom:mini-graph-card
            aggregate_func: max
            font_size_header: 10
            hours_to_show: 7
            line_width: 2
            points_per_hour: 10
            smoothing: false
            update_interval: 30
            show:
              average: true
              extrema: true
            entities:
              - entity: sensor.glances_cpu_used
                color: var(--complement-color-one)
                name: System
              - entity: sensor.glances_containers_cpu_used
                color: var(--complement-color-two)
                name: Containers

          - name: RAM Usage
            type: custom:mini-graph-card
            aggregate_func: max
            font_size_header: 10
            hours_to_show: 7
            line_width: 2
            points_per_hour: 10
            smoothing: false
            update_interval: 30
            show:
              average: true
              extrema: true
            entities:
              - entity: sensor.glances_ram_used
                color: var(--complement-color-one)
                name: System
              - entity: sensor.glances_containers_ram_used
                color: var(--complement-color-two)
                name: Containers

      - title: Disk Usage
        type: custom:vertical-stack-in-card
        cards:
          - type: custom:bar-card
            style: |
              .card-content {
                padding-bottom: 0;
              }
            direction: up
            height: 100px
            max: 100
            min: 0
            positions:
              icon: inside
              title: inside
              value: inside
            severity:
              - color: "#2DAD4B"
                from: 0
                to: 30
              - color: "#2AA246"
                from: 30
                to: 40
              - color: "#FFAE03"
                from: 40
                to: 50
              - color: "#CC8B00"
                from: 50
                to: 60
              - color: "#D37209"
                from: 60
                to: 70
              - color: "#D95812"
                from: 70
                to: 80
              - color: "#E52424"
                from: 80
                to: 90
              - color: "#C91818"
                from: 90
                to: 100
            show_icon: true
            stack: horizontal
            tap_action: none
            entities:
              - entity: sensor.glances_used_percent
                name: SSD
              - entity: sensor.glances_mnt_media01_used_percent
                name: Media 01
              - entity: sensor.glances_mnt_media02_used_percent
                name: Media 02
              - entity: sensor.glances_mnt_media03_used_percent
                name: Media 03
          - title: free space
            type: entities
            style: |
              .card-header {
                padding-top: 0;
              }
            entities:
              - entity: sensor.glances_free
                name: SSD
              - entity: sensor.glances_mnt_media01_free
                name: Media 01
              - entity: sensor.glances_mnt_media02_free
                name: Media 02
              - entity: sensor.glances_mnt_media03_free
                name: Media 03

      - break

      # example code to show docker containers that are running
      - type: custom:auto-entities
        filter:
          include:
            - entity_id: '*docker*'
              state: "on"
        show_empty: false
        sort:
          method: name
          numeric: true
        card:
          type: glance
          title: Docker Containers Running
          show_state: false
          columns: 3

      # example code to show docker containers that are not running
      - type: custom:auto-entities
        filter:
          include:
            - entity_id: '*docker*'
              state: "off"
        show_empty: false
        sort:
          method: name
          numeric: true
        card:
          type: glance
          title: Docker Containers Stopped
          show_state: false
          columns: 3

      # - title: Docker
      #   show_header_toggle: false
      #   type: entities
      #   entities:
      #     - entity: sensor.docker_mosquitto_state
      #       name: Mosquitto
      #     - entity: sensor.docker_nodered_state
      #       name: Node-RED
      #     - entity: sensor.docker_mariadb_state
      #       name: MariaDB
      #     - entity: sensor.docker_influxdb_state
      #       name: InfluxDB
      #     - entity: sensor.docker_deepstack_state
      #       name: Deep Stack
      #     - entity: sensor.docker_esphome_state
      #       name: ESPHome
      #     - entity: sensor.docker_tasmoadmin_state
      #       name: TasmoAdmin

      - break



      - type: custom:auto-entities
        card:
          type: entities
          title: Network Switches
        filter:
          include:
            - entity_id: "switch.*_unifi"

      - type: custom:auto-entities
        card:
          type: entities
          title: ZWave Network
        filter:
          include:
            - domain: zwave

      - break

      - title: Swart Ninja 02
        type: entities
        show_header_toggle: false
        entities:
          - entity: script.shutdown_swartninja02
            name: Shutdown
          - switch.deluge_switch
          - sensor.deluge_down_speed
          - sensor.deluge_up_speed
          - sensor.deluge_status

      - title: Swart Ninja 03
        type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.blue_iris_state
          - input_boolean.blue_iris



