wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_verbose_name} Hotspot
    password: !secret wifi_ap_password
