---
wifi:
  ssid: !secret wifi_upstairs_not_ssid
  password: !secret wifi_upstairs_not_password
  fast_connect: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_verbose_name}
    password: !secret wifi_ap_password

# wifi:
#   fast_connect: true
#   networks:
#     - ssid: !secret wifi_not_ssid
#       password: !secret wifi_not_password
#       bssid: !secret wifi_hall_not_bssid
#       hidden: true
#       priority: 0

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: ${device_verbose_name}
#     password: !secret wifi_ap_password
