substitutions:
  node_name: kitchen_side
  node_comment: Sonoff Basic 17FEDB
  device_verbose_name: Kitchen Side

packages:
  wifi: !include common/wifi/not.hall.yaml
  device_base: !include common/sonoff_basic_base_light.yaml