---
substitutions:
  node_name: kitchen_side
  node_comment: Sonoff Basic 17FEDB
  device_verbose_name: Kitchen Side
  switch_icon: mdi:track-light

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
