---
substitutions:
  node_name: living_room_cupboard_plug
  node_comment: DETA 2G Plug
  device_verbose_name: Living Room Cupboard Plug
  switch_icon: mdi:power-socket-au

packages:
  wifi: !include common/wifi/not.upstairs.yaml
  device_base: !include common/delta_grid_smart_plug_2g_base.yaml

binary_sensor:
# Button on the Sonoff Basic
- platform: gpio
  id: button_01
  pin:
    number: GPIO16
    mode: INPUT_PULLUP
    inverted: true
  on_press:
    - switch.toggle: relay_01
- platform: gpio
  id: button_02
  pin:
    number: GPIO12
    mode: INPUT_PULLUP
    inverted: true
  on_press:
    - switch.toggle: relay_02

switch:
- platform: gpio
  pin: GPIO13
  id: relay_01
  name: ${device_verbose_name} 01
  icon: ${switch_icon}
- platform: gpio
  pin: GPIO14
  id: relay_02
  name: ${device_verbose_name} 02
  icon: ${switch_icon}
  restore_mode: ALWAYS_ON