substitutions:
  node_name: man_cave_kitchen_ceiling_two
  device_verbose_name: Man Cave Kitchen Ceiling Two

packages:
  wifi: !include common/wifi.man_cave.yaml
  device_base: !include common/sonoff_basic_base_light.yaml