---
substitutions:
  node_name: man_cave_kitchen_ceiling_two
  node_comment: 'ID: 0F6E67'
  device_verbose_name: Man Cave Kitchen Ceiling Two
  switch_icon: mdi:track-light

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
