---
substitutions:
  node_name: sonoff_basic_35d32e
  node_comment: Sonoff Basic 35D32E
  device_verbose_name: Sonoff Basic 35D32E
  switch_icon: mdi:light-switch

packages:
  wifi: !include common/wifi/main.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
