---
substitutions:
  device_verbose_name: Work Station
  node_comment: "Work Station (ID: 671FAA)"
  node_name: work_station
  switch_icon: mdi:soldering-iron

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
