---
##################################################################################################################
# Home Assistant Frontend
# This offers the official frontend to control Home Assistant.
#
# URL: https://www.home-assistant.io/integrations/frontend/
##################################################################################################################
frontend:
  # List of additional resources to load in latest javascript mode.
  extra_html_url: []

  # List of additional javascript code to load in es5 javascript mode.
  extra_html_url_es5: []

  # Allow to define different themes. See below for further details.
  themes: !include_dir_merge_named ../themes
