---
##################################################################################################################
# Lovelace
# Lovelace is the Home Assistant user interface. It’s a fast, customizable and powerful way for users to
# manage their homes, working on mobile or desktop.
#
# URL: https://www.home-assistant.io/lovelace/
# URL: https://www.home-assistant.io/lovelace/yaml-mode/
##################################################################################################################
lovelace:
  mode: yaml
  resources:
    - url: /local/custom_cards/invisible-card/invisible-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/cover-control-button-row/cover-control-button-row.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/scheduler-card/scheduler-card.js?v=0
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
  dashboards:
    lovelace-admin:
      mode: yaml
      filename: ui-lovelace-admin.yaml
      title: Admin
      icon: mdi:account-lock
      show_in_sidebar: true
      require_admin: true
