---
##################################################################################################################
# lovelace_gen
# Improve the lovelace yaml parser for Home Assistant.
#
# URL: https://github.com/thomasloven/hass-lovelace_gen
##################################################################################################################
lovelace_gen: ~
