---
##################################################################################################################
# Lovelace
# Lovelace is the Home Assistant user interface. It’s a fast, customizable and powerful way for users to
# manage their homes, working on mobile or desktop.
#
# URL: https://www.home-assistant.io/lovelace/
# URL: https://www.home-assistant.io/lovelace/yaml-mode/
##################################################################################################################
lovelace:
  mode: storage
  dashboards:
    swart-ninja-dashboard:
      mode: yaml
      title: SNSH
      icon: mdi:ninja
      show_in_sidebar: true
      filename: swart-ninja-dashboard.yaml
    swart-ninja-admin-dashboard:
      mode: yaml
      title: Admin
      icon: mdi:account-lock
      show_in_sidebar: true
      require_admin: true
      filename: swart-ninja-admin-dashboard.yaml