---
##################################################################################################################
# Monitor Docker
# The Monitor Docker allows you to monitor Docker and container statistics and turn on/off containers.
# It can connected to the Docker daemon locally or remotely.
#
# URL: https://github.com/ualex73/monitor_docker
##################################################################################################################
monitor_docker:
  - name: Docker
    containers:
      - apprise
      - chronograf
      - deepstack
      - duplicati
      - esphome
      - grafana
      - homeassistant
      - influxdb
      - mariadb
      - mariadb-backup
      - minecraft-server-01
      - minecraft-server-02
      - minecraft-server-03
      - mosquitto
      - nodered
      - plexmediaserver
      - portainer
      - radarr
      - sonarr
      - tasmoadmin
      - unifi-controller
      - watchtower
      - xboxone
      - xteve
    rename:
      apprise: AppRise
      chronograf: Chronograf
      deepstack: Deep Stack
      duplicati: Duplicati
      esphome: ESPHome
      grafana: Grafana
      homeassistant: Home Assistant
      influxdb: InfluxDB
      mariadb-backup: MariaDB Backup
      mariadb: MariaDB
      minecraft-server-01: Minecraft Server 01
      minecraft-server-02: Minecraft Server 02
      minecraft-server-03: Minecraft Server 03
      mosquitto: Mosquitto
      nodered: Node-RED
      plexmediaserver: Plex Media Server
      portainer: Portainer
      radarr: Radarr
      sonarr: Sonarr
      tasmoadmin: TasmoAdmin
      unifi-controller: UniFi Controller
      watchtower: Watchtower
      xboxone: Xbox One
      xteve: Xteve