---
##############################################################################################
# InfluxDB include entities
# Configure which integrations should be included in recordings to InfluxDB.
# If set, all other entities will not be recorded to InfluxDB. Values set by the exclude
# lists will take precedence.
#
# URL: https://www.home-assistant.io/integrations/influxdb/#include
##############################################################################################
- binary_sensor.kitchen_multisensor_motion
- binary_sensor.kitchen_motion_led_motion
- binary_sensor.kitchen_motion
- sensor.kitchen_motion_led_wifi_signal
- sensor.kitchen_multisensor_wifi_signal
- sensor.kitchen_multisensor_humidity
- sensor.kitchen_multisensor_luminance
- sensor.kitchen_multisensor_temperature

- sensor.kitchen_dryer_current
- sensor.kitchen_dryer_power
- sensor.kitchen_dryer_voltage
- sensor.kitchen_dryer_total_daily_energy
- sensor.kitchen_dryer_yearly_energy_peak

- sensor.kitchen_washing_machine_current
- sensor.kitchen_washing_machine_power
- sensor.kitchen_washing_machine_voltage
- sensor.kitchen_washing_machine_total_daily_energy
- sensor.kitchen_washing_machine_yearly_energy_peak

- sensor.kitchen_refrigerator_current
- sensor.kitchen_refrigerator_power
- sensor.kitchen_refrigerator_voltage
- sensor.kitchen_refrigerator_total_daily_energy
- sensor.kitchen_refrigerator_yearly_energy_peak
