---
id: bathroom_light_off_motion
alias: Bathroom Light Off Motion
description: Turn off bathroom light 5 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.bathroom_multisensor_motion
  to: 'off'
  for:
    minutes: 5
condition:
  - condition: state
    entity_id: light.bathroom_zw111_nano_dimmer
    state: 'on'
action:
  - service: light.turn_off
    entity_id: light.bathroom_zw111_nano_dimmer
